// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package tb_user_relation

import (
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/os/gtime"
)

// Entity is the golang structure for table tb_user_relation.
type Entity struct {
    Id           int         `orm:"id,primary"     json:"id"`             // 主键           
    UserId       int64       `orm:"user_id"        json:"user_id"`        // 用户ID         
    UserParentId int64       `orm:"user_parent_id" json:"user_parent_id"` // 上级用户ID     
    LevelRight   int         `orm:"level_right"    json:"level_right"`    // 用户层数       
    LevelLeft    int         `orm:"level_left"     json:"level_left"`     // 用户层数       
    Area         int         `orm:"area"           json:"area"`           // 0:左区 1:右区  
    SubLeft      float64     `orm:"sub_left"       json:"sub_left"`       // 左区业绩       
    SubRight     float64     `orm:"sub_right"      json:"sub_right"`      // 右区业绩       
    Total        float64     `orm:"total"          json:"total"`          // 业绩           
    TotalAbs     float64     `orm:"total_abs"      json:"total_abs"`      // 量碰业绩       
    CreateTime   *gtime.Time `orm:"create_time"    json:"create_time"`    //                
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (r *Entity) OmitEmpty() *arModel {
	return Model.Data(r).OmitEmpty()
}

// Inserts does "INSERT...INTO..." statement for inserting current object into table.
func (r *Entity) Insert() (result sql.Result, err error) {
	return Model.Data(r).Insert()
}

// InsertIgnore does "INSERT IGNORE INTO ..." statement for inserting current object into table.
func (r *Entity) InsertIgnore() (result sql.Result, err error) {
	return Model.Data(r).InsertIgnore()
}

// Replace does "REPLACE...INTO..." statement for inserting current object into table.
// If there's already another same record in the table (it checks using primary key or unique index),
// it deletes it and insert this one.
func (r *Entity) Replace() (result sql.Result, err error) {
	return Model.Data(r).Replace()
}

// Save does "INSERT...INTO..." statement for inserting/updating current object into table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Save() (result sql.Result, err error) {
	return Model.Data(r).Save()
}

// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Update() (result sql.Result, err error) {
	return Model.Data(r).Where(gdb.GetWhereConditionOfStruct(r)).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
func (r *Entity) Delete() (result sql.Result, err error) {
	return Model.Where(gdb.GetWhereConditionOfStruct(r)).Delete()
}