// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package goods_kline_hour_1__info

// Fill with you ideas below.