// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package tb_posts

import (
	"github.com/gogf/gf/frame/g"
	"github.com/zzzhangjian/go_ece/library/response"
)

type PostPageRequest struct {
	response.PageRequest
	Type Type
}

type Type string

const (
	AD     Type = "AD"
	Banner Type = "BANNER"
	Notice Type = "NOTICE"
)

// Fill with you ideas below.
// 分页查询
func Page(request PostPageRequest) (*response.PageResult, error) {
	condition := &g.Map{
		"post_type": request.Type,
	}
	total, err := Model.Where(condition).Count()
	if err != nil {
		return nil, err
	}
	list, err := Model.Where(condition).Limit(request.PageSize).Offset((request.PageNum - 1) * request.PageSize).FindAll()
	if err != nil {
		return nil, err
	}
	result := &response.PageResult{
		PageRequest: request.PageRequest,
		Total:       total,
		List:        list,
	}
	return result, err
}
